// 与 apps/api/src/ai-settings/builtin-catalog.ts 保持同步。
// 静态数据，前端直接内联以避免额外 fetch + 在后端未就绪时也能展示。
import type { BuiltinProviderTemplate } from './api';

export const BUILTIN_PROVIDER_CATALOG: BuiltinProviderTemplate[] = [
  {
    id: 'anthropic',
    label: 'Anthropic',
    providerType: 'ANTHROPIC',
    baseUrl: 'https://api.anthropic.com',
    defaultModels: ['claude-sonnet-4-6', 'claude-opus-4-7'],
    supportsWebSearch: true,
    supportsTools: true,
    iconColor: '#d97757',
    iconText: 'A',
  },
  {
    id: 'openai',
    label: 'OpenAI',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://api.openai.com/v1',
    defaultModels: ['gpt-4o', 'gpt-4o-mini'],
    supportsWebSearch: true,
    supportsTools: true,
    iconColor: '#10a37f',
    iconText: 'O',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://api.deepseek.com/v1',
    defaultModels: ['deepseek-chat', 'deepseek-reasoner'],
    supportsWebSearch: false,
    supportsTools: false,
    iconColor: '#4d6bfe',
    iconText: 'D',
  },
  {
    id: 'qwen',
    label: '通义千问',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultModels: ['qwen-max', 'qwen-plus'],
    supportsWebSearch: false,
    supportsTools: true,
    iconColor: '#615ced',
    iconText: 'Q',
  },
  {
    id: 'kimi',
    label: 'Kimi (Moonshot)',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://api.moonshot.cn/v1',
    defaultModels: ['moonshot-v1-8k', 'moonshot-v1-32k'],
    supportsWebSearch: false,
    supportsTools: false,
    iconColor: '#000000',
    iconText: 'K',
  },
  {
    id: 'zhipu',
    label: '智谱 GLM',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    defaultModels: ['glm-4-plus'],
    supportsWebSearch: false,
    supportsTools: true,
    iconColor: '#1e40af',
    iconText: '智',
  },
  {
    id: 'doubao',
    label: '豆包 (火山方舟)',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    defaultModels: [],
    supportsWebSearch: false,
    supportsTools: true,
    iconColor: '#f55036',
    iconText: '豆',
  },
  {
    id: 'groq',
    label: 'Groq',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://api.groq.com/openai/v1',
    defaultModels: ['llama-3.3-70b-versatile'],
    supportsWebSearch: false,
    supportsTools: true,
    iconColor: '#f97316',
    iconText: 'G',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModels: [],
    supportsWebSearch: false,
    supportsTools: true,
    iconColor: '#6366f1',
    iconText: 'R',
  },
  {
    id: 'xiaomi',
    label: '小米 MiMo',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: '',
    defaultModels: ['mimo-7b'],
    supportsWebSearch: false,
    supportsTools: false,
    iconColor: '#ff6900',
    iconText: '米',
  },
  {
    id: 'ollama',
    label: 'Ollama (本地)',
    providerType: 'OPENAI_COMPATIBLE',
    baseUrl: 'http://localhost:11434/v1',
    defaultModels: [],
    supportsWebSearch: false,
    supportsTools: true,
    iconColor: '#000000',
    iconText: 'O',
  },
];
